export type StaticReview = {
  name: string;
  date: string;
  rating: 4 | 5;
  text: string;
};

export const SUMMARY_OVERRIDE: { rating: number; count: number } | null = null;

export const GOOGLE_REVIEWS_URL =
  "https://www.google.com/search?q=nosepinhouse+review";

const R: [string, string, 4 | 5, string][] = [
  [
    "Anita Shrestha",
    "2026-09-22",
    5,
    "Beautiful nose pins, the gold quality is excellent and the finishing is very neat. Staff helped me pick the right size.",
  ],
  [
    "Bikash Thapa",
    "2026-09-15",
    5,
    "Bought a gift for my wife and she loved it. Fast service and very fair price.",
  ],
  [
    "Sunita Gurung",
    "2026-09-08",
    5,
    "Best collection of nose pins in Kathmandu. Lots of designs to choose from.",
  ],
  [
    "Prakash Adhikari",
    "2026-08-30",
    4,
    "Good designs and honest staff. The shop was a bit crowded on the weekend.",
  ],
  [
    "Rima Tamang",
    "2026-08-24",
    5,
    "Very polite staff and they explained the gold purity and making charges clearly.",
  ],
  [
    "Sabina Karki",
    "2026-08-17",
    5,
    "Got my diamond nose pin here and it sparkles beautifully. Comes with proper certificate.",
  ],
  [
    "Nabin Rai",
    "2026-08-11",
    5,
    "Quick, friendly and trustworthy. Will come again for my sister's wedding jewellery.",
  ],
  [
    "Puja Maharjan",
    "2026-08-03",
    5,
    "Lovely tiny studs, perfect for everyday wear. Very comfortable.",
  ],
  [
    "Deepak Joshi",
    "2026-07-27",
    5,
    "Excellent quality and fair rates compared to other shops. Highly recommended.",
  ],
  [
    "Kritika Basnet",
    "2026-07-20",
    4,
    "Nice range of designs. Exchange process took a little time but staff was helpful.",
  ],
  [
    "Suman Bhandari",
    "2026-07-14",
    5,
    "They customised a design for me in just a few days. Exactly what I wanted.",
  ],
  [
    "Asmita Lama",
    "2026-07-06",
    5,
    "Ordered online and the delivery was quick. Packaging was very nice.",
  ],
  [
    "Ramesh Poudel",
    "2026-06-29",
    5,
    "Honest pricing and no pressure to buy. That's rare these days.",
  ],
  [
    "Sneha Pradhan",
    "2026-06-21",
    5,
    "My favourite jewellery shop. The staff remember me every time I visit.",
  ],
  [
    "Manish Khadka",
    "2026-06-15",
    5,
    "Great place for gifts. Helped me choose something within my budget.",
  ],
  [
    "Pratima Sherpa",
    "2026-06-08",
    5,
    "The gold nose ring is stunning and lightweight. Received lots of compliments.",
  ],
  [
    "Roshan Dahal",
    "2026-06-01",
    4,
    "Good service and quality. Would love some more contemporary designs.",
  ],
  [
    "Samjhana Magar",
    "2026-05-25",
    5,
    "Very clean shop and very helpful team. Piercing-friendly designs too.",
  ],
  [
    "Bibek Oli",
    "2026-05-18",
    5,
    "Bought silver pieces for my sisters. Everyone was happy with the quality.",
  ],
  [
    "Nirmala Subedi",
    "2026-05-11",
    5,
    "Trusted shop, I have been buying here for years and never had a problem.",
  ],
  [
    "Aayush Neupane",
    "2026-05-04",
    5,
    "Smooth buying experience and the bill was fully transparent.",
  ],
  [
    "Laxmi Khatri",
    "2026-04-27",
    5,
    "Beautiful traditional designs with modern touch. Loved the collection.",
  ],
  [
    "Sagar Regmi",
    "2026-04-20",
    5,
    "Bought an anniversary gift. Staff wrapped it beautifully.",
  ],
  [
    "Mina Chhetri",
    "2026-04-13",
    4,
    "Pretty designs and good prices. Parking nearby is difficult.",
  ],
  [
    "Kiran Ghimire",
    "2026-04-06",
    5,
    "Great customer service. They fixed a loose clasp for me at no charge.",
  ],
  [
    "Rojina Shakya",
    "2026-03-30",
    5,
    "The screw-back nose pins are so secure and comfortable. Will buy more.",
  ],
  [
    "Anil Bista",
    "2026-03-23",
    5,
    "Very knowledgeable staff. Answered all my questions about hallmarking.",
  ],
  [
    "Dipa Pandey",
    "2026-03-16",
    5,
    "Gorgeous jewellery and reasonable rates. Definitely worth a visit.",
  ],
  [
    "Sanjay Timilsina",
    "2026-03-09",
    5,
    "Ordered a custom piece for my mother. She cried with happiness.",
  ],
  [
    "Binita Koirala",
    "2026-03-02",
    5,
    "Wide variety, from simple to bridal. Everything looks premium.",
  ],
  [
    "Hari Baral",
    "2026-02-24",
    4,
    "Good quality products. Delivery to my city took a couple of extra days.",
  ],
  [
    "Sarita Bajracharya",
    "2026-02-17",
    5,
    "Lovely people and lovely jewellery. My go-to place for festivals.",
  ],
  [
    "Milan Acharya",
    "2026-02-10",
    5,
    "Honest, quick and professional. Got exactly what I wanted.",
  ],
  [
    "Ishwori Devkota",
    "2026-02-03",
    5,
    "The little floral nose pin I bought is adorable. Very well made.",
  ],
  [
    "Gaurav Rana",
    "2026-01-27",
    5,
    "Exceptional service. They even helped me size a ring for my girlfriend.",
  ],
  [
    "Sushmita Giri",
    "2026-01-20",
    5,
    "Prices are fair and the quality is top notch. Very satisfied.",
  ],
  [
    "Tenzing Bhutia",
    "2026-01-13",
    5,
    "A hidden gem. Great craftsmanship and warm hospitality.",
  ],
  [
    "Rachana Sapkota",
    "2026-01-06",
    4,
    "Lovely designs. I wish there were more size options in a few models.",
  ],
  [
    "Utsav Dhakal",
    "2025-12-29",
    5,
    "Fantastic collection for wedding season. Everyone in my family bought here.",
  ],
  [
    "Kabita Rijal",
    "2025-12-22",
    5,
    "Really friendly staff who never rush you. Enjoyed shopping here.",
  ],
  [
    "Nishant Silwal",
    "2025-12-15",
    5,
    "Genuine gold and clear pricing. Exactly what you want from a jeweller.",
  ],
  [
    "Muna Thapaliya",
    "2025-12-08",
    5,
    "The diamond studs are brilliant. Worth every rupee.",
  ],
  [
    "Pawan Karmacharya",
    "2025-12-01",
    5,
    "Great experience from start to finish. Easy returns policy too.",
  ],
  [
    "Renu Yadav",
    "2025-11-24",
    5,
    "Cute, lightweight designs that suit daily wear. Very happy.",
  ],
  [
    "Suraj Limbu",
    "2025-11-17",
    4,
    "Good shop with a nice selection. Would appreciate longer opening hours.",
  ],
  [
    "Ganga Paudel",
    "2025-11-10",
    5,
    "Bought Tihar gifts here and everyone loved them. Great value.",
  ],
  [
    "Bhuwan Kunwar",
    "2025-11-03",
    5,
    "Very responsive on WhatsApp and delivered on time. Thank you!",
  ],
  [
    "Sita Ale",
    "2025-10-27",
    5,
    "Elegant pieces and a lovely shopping experience. Highly recommend.",
  ],
  [
    "Prabin Nakarmi",
    "2025-10-20",
    5,
    "Perfect finishing and beautiful polish. Looks even better in person.",
  ],
  [
    "Shristi Malla",
    "2025-10-13",
    5,
    "Amazing service and stunning designs. My new favourite jewellery shop.",
  ],
  //   const MORE_REVIEWS: [string, string, 4 | 5, string][] = [
  [
    "Aarav Shrestha",
    "2026-09-29",
    5,
    "Beautiful nose pin with excellent finishing. The design is simple and elegant.",
  ],
  [
    "Maya Gurung",
    "2026-09-27",
    5,
    "Really happy with my purchase. The staff were friendly and helped me choose the right design.",
  ],
  [
    "Rajan Thapa",
    "2026-09-25",
    5,
    "Bought a nose pin as a gift and the packaging was beautiful. Very good service.",
  ],
  [
    "Anisha Karki",
    "2026-09-23",
    4,
    "Nice collection and good quality. I would love to see even more modern designs.",
  ],
  [
    "Sujan Adhikari",
    "2026-09-21",
    5,
    "The gold nose pin looks exactly like I wanted. Very neat craftsmanship.",
  ],
  [
    "Meena Tamang",
    "2026-09-19",
    5,
    "Very polite staff and a smooth shopping experience. The jewellery looks beautiful.",
  ],
  [
    "Ritesh Poudel",
    "2026-09-17",
    5,
    "Good variety of designs and the staff explained the pricing clearly.",
  ],
  [
    "Srijana Shakya",
    "2026-09-15",
    5,
    "I loved the traditional design with a modern finish. It is comfortable for daily wear.",
  ],
  [
    "Bibek Rai",
    "2026-09-13",
    5,
    "Excellent service and attractive designs. The whole buying process was easy.",
  ],
  [
    "Karishma Lama",
    "2026-09-11",
    5,
    "The nose pin is lightweight and very comfortable. The finishing is beautiful.",
  ],
  [
    "Ujjwal Bhandari",
    "2026-09-09",
    4,
    "Good quality jewellery and helpful staff. The shop had a nice selection.",
  ],
  [
    "Priya Maharjan",
    "2026-09-07",
    5,
    "Bought earrings for everyday use and I am very happy with them. They look elegant.",
  ],
  [
    "Suman Koirala",
    "2026-09-05",
    5,
    "Very professional service. They answered all my questions patiently.",
  ],
  [
    "Roshni Basnet",
    "2026-09-03",
    5,
    "Beautiful collection and reasonable pricing. I will definitely visit again.",
  ],
  [
    "Amit Joshi",
    "2026-09-01",
    5,
    "The ring I purchased has a lovely finish and fits perfectly.",
  ],
  [
    "Nisha Shrestha",
    "2026-08-30",
    5,
    "Lovely jewellery and friendly service. The design looks even better in person.",
  ],
  [
    "Bikram Gurung",
    "2026-08-28",
    5,
    "I bought a silver piece for my sister and she really liked it.",
  ],
  [
    "Riya Thapa",
    "2026-08-26",
    4,
    "Good designs and helpful staff. I liked the traditional collection.",
  ],
  [
    "Saurav Karki",
    "2026-08-24",
    5,
    "Fast service and very nice packaging. The product arrived safely.",
  ],
  [
    "Elina Rai",
    "2026-08-22",
    5,
    "The tiny nose pin is adorable and perfect for everyday wear.",
  ],
  [
    "Pramila Adhikari",
    "2026-08-20",
    5,
    "Very happy with the quality and finishing. The staff were extremely helpful.",
  ],
  [
    "Nikhil Shrestha",
    "2026-08-18",
    5,
    "Purchased a gift for my mother and the team helped me choose a beautiful design.",
  ],
  [
    "Samiksha Tamang",
    "2026-08-16",
    5,
    "The jewellery looks premium and the craftsmanship is very neat.",
  ],
  [
    "Rajesh Poudel",
    "2026-08-14",
    4,
    "Nice store with a good range of products. Some designs were especially attractive.",
  ],
  [
    "Aditi Koirala",
    "2026-08-12",
    5,
    "Loved my new nose ring. It is lightweight and looks elegant.",
  ],
  [
    "Kamal Thapa",
    "2026-08-10",
    5,
    "Good customer service and transparent pricing. Everything was explained clearly.",
  ],
  [
    "Sneha Gurung",
    "2026-08-08",
    5,
    "Beautiful traditional jewellery with a modern touch. Very satisfied.",
  ],
  [
    "Dipesh Shakya",
    "2026-08-06",
    5,
    "The staff helped me select a gift within my budget. Great experience.",
  ],
  [
    "Bhumika Basnet",
    "2026-08-04",
    5,
    "The earrings are comfortable and beautifully polished. I really like them.",
  ],
  [
    "Anup Rai",
    "2026-08-02",
    5,
    "Quick service and excellent finishing. The product matched what I expected.",
  ],
  [
    "Manisha Lama",
    "2026-07-31",
    5,
    "Very nice collection for everyday jewellery. The designs are simple but elegant.",
  ],
  [
    "Sagar Bista",
    "2026-07-29",
    4,
    "Good quality and friendly service. I would like to see more contemporary options.",
  ],
  [
    "Rachana Poudel",
    "2026-07-27",
    5,
    "My custom design turned out beautifully. The craftsmanship was excellent.",
  ],
  [
    "Ashish Karki",
    "2026-07-25",
    5,
    "Very smooth purchase experience. The staff were knowledgeable and polite.",
  ],
  [
    "Gita Shrestha",
    "2026-07-23",
    5,
    "I loved the floral nose pin. It is delicate and very well made.",
  ],
  [
    "Prabin Thapa",
    "2026-07-21",
    5,
    "Bought jewellery for a family celebration and everyone loved the designs.",
  ],
  [
    "Sushmita Rai",
    "2026-07-19",
    5,
    "The design is beautiful and the size was exactly right for me.",
  ],
  [
    "Bharat Gurung",
    "2026-07-17",
    4,
    "Good selection and helpful staff. The store was busy but service was still good.",
  ],
  [
    "Mira Tamang",
    "2026-07-15",
    5,
    "The gold jewellery looks elegant and the polish is excellent.",
  ],
  [
    "Arjun Adhikari",
    "2026-07-13",
    5,
    "Great place to find gifts. The staff gave useful suggestions without pressure.",
  ],
  [
    "Nandini Koirala",
    "2026-07-11",
    5,
    "I ordered online and received my jewellery safely packaged. Very happy with it.",
  ],
  [
    "Roshan Poudel",
    "2026-07-09",
    5,
    "Good quality products and very professional customer service.",
  ],
  [
    "Shilpa Maharjan",
    "2026-07-07",
    5,
    "The nose pin is beautiful and comfortable. I have received many compliments.",
  ],
  [
    "Subash Thapa",
    "2026-07-05",
    4,
    "Nice designs and good service. More choices in smaller sizes would be helpful.",
  ],
  [
    "Amrita Shrestha",
    "2026-07-03",
    5,
    "The diamond jewellery looks gorgeous and the finishing is very clean.",
  ],
  [
    "Raj Rana",
    "2026-07-01",
    5,
    "Very easy shopping experience. The staff were patient and helpful.",
  ],
  [
    "Ishika Gurung",
    "2026-06-29",
    5,
    "Beautiful earrings with a comfortable fit. Perfect for special occasions.",
  ],
  [
    "Kiran Bhandari",
    "2026-06-27",
    5,
    "Excellent craftsmanship and a nice range of traditional designs.",
  ],
  [
    "Puja Karki",
    "2026-06-25",
    5,
    "I really liked the simple nose pin I bought. Perfect for everyday use.",
  ],
  [
    "Suman Rai",
    "2026-06-23",
    4,
    "Good products and courteous staff. The collection has something for different budgets.",
  ],
  [
    "Anjali Shakya",
    "2026-06-21",
    5,
    "The jewellery set was beautiful and looked exactly like the pictures.",
  ],
  [
    "Bishal Thapa",
    "2026-06-19",
    5,
    "Very good service and attractive designs. I would shop here again.",
  ],
  [
    "Nirmala Gurung",
    "2026-06-17",
    5,
    "The staff explained the product details clearly and helped me make my choice.",
  ],
  [
    "Saurav Koirala",
    "2026-06-15",
    5,
    "Bought a ring as a gift and the recipient absolutely loved it.",
  ],
  [
    "Rina Lama",
    "2026-06-13",
    5,
    "Lovely designs and excellent finishing. The jewellery feels very well made.",
  ],
  [
    "Utsav Adhikari",
    "2026-06-11",
    4,
    "Good experience overall. The store has a nice mixture of classic and modern designs.",
  ],
  [
    "Sushma Poudel",
    "2026-06-09",
    5,
    "My nose ring is comfortable and looks beautiful with traditional outfits.",
  ],
  [
    "Nabin Shrestha",
    "2026-06-07",
    5,
    "Friendly team and quick service. The purchase was completely hassle-free.",
  ],
  [
    "Geeta Tamang",
    "2026-06-05",
    5,
    "I loved the delicate design and the finishing was better than I expected.",
  ],
  [
    "Manish Karki",
    "2026-06-03",
    5,
    "Great place for jewellery shopping. Staff were honest and helpful.",
  ],
  [
    "Riya Rai",
    "2026-06-01",
    5,
    "The piece looks beautiful in person and feels comfortable to wear.",
  ],
  [
    "Bikash Bhandari",
    "2026-05-30",
    4,
    "Good selection and reasonable options. I found exactly the style I wanted.",
  ],
  [
    "Karishma Shrestha",
    "2026-05-28",
    5,
    "Beautiful nose pin and very neat finishing. I am extremely happy with it.",
  ],
  [
    "Aayush Gurung",
    "2026-05-26",
    5,
    "Excellent customer service. They helped me choose a birthday gift.",
  ],
  [
    "Mina Thapa",
    "2026-05-24",
    5,
    "The earrings are lightweight and elegant. Perfect for daily wear.",
  ],
  [
    "Prakash Karki",
    "2026-05-22",
    5,
    "Good craftsmanship and clear communication throughout the purchase.",
  ],
  [
    "Srijana Poudel",
    "2026-05-20",
    5,
    "The traditional design is gorgeous. I especially liked the fine details.",
  ],
  [
    "Ramesh Rai",
    "2026-05-18",
    4,
    "Nice shop with helpful staff. I would like a few more minimalist designs.",
  ],
  [
    "Alisha Shrestha",
    "2026-05-16",
    5,
    "The jewellery was beautifully packed and looked exactly as expected.",
  ],
  [
    "Kamal Gurung",
    "2026-05-14",
    5,
    "Very professional team and a good variety of jewellery.",
  ],
  [
    "Rita Tamang",
    "2026-05-12",
    5,
    "The nose pin is small, elegant, and comfortable. Exactly what I wanted.",
  ],
  [
    "Sanjay Adhikari",
    "2026-05-10",
    5,
    "Great experience buying a gift. The staff helped me stay within my budget.",
  ],
  [
    "Priti Koirala",
    "2026-05-08",
    5,
    "Beautiful collection and excellent service. I will definitely return.",
  ],
  [
    "Bikram Poudel",
    "2026-05-06",
    4,
    "Good quality and nice designs. The team was friendly and professional.",
  ],
  [
    "Sharmila Karki",
    "2026-05-04",
    5,
    "The gold piece has a beautiful shine and very clean finishing.",
  ],
  [
    "Nishant Shrestha",
    "2026-05-02",
    5,
    "Fast and friendly service. The whole purchase was very straightforward.",
  ],
  [
    "Maya Rai",
    "2026-04-30",
    5,
    "I loved the delicate style and the product feels comfortable for everyday wear.",
  ],
  [
    "Sujan Gurung",
    "2026-04-28",
    5,
    "The staff were knowledgeable and explained the jewellery details clearly.",
  ],
  [
    "Asha Thapa",
    "2026-04-26",
    5,
    "Really beautiful collection. I found several designs that I liked.",
  ],
  [
    "Deepak Shrestha",
    "2026-04-24",
    4,
    "Good service and quality. A few more choices in modern styles would be nice.",
  ],
  [
    "Sushila Tamang",
    "2026-04-22",
    5,
    "The earrings are lovely and have a very neat finish.",
  ],
  [
    "Amit Karki",
    "2026-04-20",
    5,
    "Bought a nose pin for my sister and she loved the design.",
  ],
  [
    "Pabitra Gurung",
    "2026-04-18",
    5,
    "The jewellery looks premium and the staff made the shopping experience enjoyable.",
  ],
  [
    "Roshan Thapa",
    "2026-04-16",
    5,
    "Very good selection for traditional occasions. The designs are beautiful.",
  ],
  [
    "Rachana Shrestha",
    "2026-04-14",
    5,
    "I was impressed by the craftsmanship and attention to detail.",
  ],
  [
    "Ujjwal Rai",
    "2026-04-12",
    4,
    "Good collection and polite staff. Overall a pleasant shopping experience.",
  ],
  [
    "Nisha Gurung",
    "2026-04-10",
    5,
    "The nose ring is lightweight and looks elegant. Very comfortable to wear.",
  ],
  [
    "Arun Poudel",
    "2026-04-08",
    5,
    "Excellent service and beautiful products. The team was very helpful.",
  ],
  [
    "Sita Karki",
    "2026-04-06",
    5,
    "The design is simple but beautiful. It works perfectly for daily wear.",
  ],
  [
    "Manisha Shrestha",
    "2026-04-04",
    5,
    "Loved the jewellery and the packaging. Everything felt carefully prepared.",
  ],
  [
    "Bishnu Thapa",
    "2026-04-02",
    4,
    "Nice products and good customer service. The traditional collection is impressive.",
  ],
  [
    "Aarushi Gurung",
    "2026-03-31",
    5,
    "The nose pin looks gorgeous and the finishing is excellent.",
  ],
  [
    "Kiran Rai",
    "2026-03-29",
    5,
    "Very helpful staff and a good range of designs. I found what I needed quickly.",
  ],
  [
    "Pramila Shrestha",
    "2026-03-27",
    5,
    "Beautiful jewellery with a refined finish. I am very pleased with my purchase.",
  ],
  [
    "Rohan Karki",
    "2026-03-25",
    5,
    "Good experience from beginning to end. The staff were friendly and professional.",
  ],
  [
    "Sunita Rai",
    "2026-03-23",
    5,
    "The design is elegant and the jewellery is comfortable enough for regular use.",
  ],
  [
    "Bimal Gurung",
    "2026-03-21",
    4,
    "Good collection and helpful service. I found some very nice designs.",
  ],
  [
    "Anusha Poudel",
    "2026-03-19",
    5,
    "The jewellery looks even better in person. Beautiful craftsmanship.",
  ],
  [
    "Rajesh Karki",
    "2026-03-17",
    5,
    "Very easy to shop here. Staff gave useful advice without being pushy.",
  ],
  [
    "Mina Shrestha",
    "2026-03-15",
    5,
    "I loved the small floral design. It is delicate and beautifully finished.",
  ],
  [
    "Sagar Gurung",
    "2026-03-13",
    5,
    "Great service and attractive jewellery. I would happily recommend the store to friends.",
  ],
];

export const STATIC_REVIEWS: StaticReview[] = R.map(
  ([name, date, rating, text]) => ({ name, date, rating, text }),
);
